/* confdefs.h */
#define PACKAGE_NAME "lplex"
#define PACKAGE_TARNAME "lplex"
#define PACKAGE_VERSION "0.3"
#define PACKAGE_STRING "lplex 0.3"
#define PACKAGE_BUGREPORT "audioplex-lpcm@lists.sourceforge.net"
#define PACKAGE_URL ""
#define PACKAGE "lplex"
#define VERSION "0.3"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_FCNTL_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_ATEXIT 1
#define HAVE_MEMSET 1
#define HAVE_PUTENV 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
