a52dec_LIB=
a52dec_LINK=
MAYBE_a52dec=
HAVE_a52dec=yes
HAVE_EXTERNAL_a52dec=@HAVE_EXTERNAL_a52dec@
CONFIGURE_a52dec_FLAGS=
a52dec_BUILD=
WITH_a52dec=@WITH_a52dec@
a52dec_DEPENDENCY=Makefile /home/fab/Desktop/dvda-author-dev/
