help2man_LIB=
help2man_LINK=
MAYBE_help2man=
HAVE_help2man=yes
HAVE_EXTERNAL_help2man=@HAVE_EXTERNAL_help2man@
CONFIGURE_help2man_FLAGS=
help2man_BUILD=
WITH_help2man=@WITH_help2man@
help2man_DEPENDENCY=Makefile /home/fab/Desktop/dvda-author-dev/
