ImageMagick_LIB=
ImageMagick_LINK=
MAYBE_ImageMagick=
HAVE_ImageMagick=@HAVE_ImageMagick@
HAVE_EXTERNAL_ImageMagick=@HAVE_EXTERNAL_ImageMagick@
CONFIGURE_ImageMagick_FLAGS=
imagemagick_BUILD=@imagemagick_BUILD@
WITH_ImageMagick=@WITH_ImageMagick@
ImageMagick_DEPENDENCY=Makefile /home/fab/Desktop/dvda-author-dev/
