FLAC_MAKESPEC=auto
FLAC_CONFIGSPEC=lib
FLAC_DEPENDENCY=Makefile libogg
FLAC_TARGETLIB=libFLAC.a

#Autoconf-substituted, do not modify#
FLAC_LIB=@FLAC_LIB@
FLAC_LINK=@FLAC_LINK@
MAYBE_FLAC=@MAYBE_FLAC@
HAVE_FLAC=@HAVE_a52_dec@
HAVE_EXTERNAL_FLAC=@HAVE_EXTERNAL_FLAC@
