man2html_LIB=
man2html_LINK=
MAYBE_man2html=
HAVE_man2html=no
HAVE_EXTERNAL_man2html=@HAVE_EXTERNAL_man2html@
CONFIGURE_man2html_FLAGS=
man2html_BUILD=
WITH_man2html=@WITH_man2html@
man2html_DEPENDENCY=Makefile /home/fab/Dev/dvda-author-dev/
