name: dvda-author

on:
  push:
    tags:
      - 'v*' 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: | 
       sudo apt -yq update
       sudo apt -yq upgrade
       sudo apt -yq install nasm util-linux curl xz-utils wkhtmltopdf
    - name: autogen
      run: chmod +x autogen && /bin/bash autogen
    - name: configure
      run: ./configure
    - name: make 
      run: sudo make PARALLEL=-j2
    - name: copy_menu
      run: | 
        sudo cp -rf menu local/ 
        sudo cp -f src/dvda-author-dev dvda-author-dev.1 local/
    - name: tar_build
      run: |
        export tag_name="${GITHUB_REF##*/}"
        sudo tar cpJvf dvda-author-${tag_name}.tar.xz local/
        
    - name: Upload Release Assets
      run: |
        set -x
        assets=()
        export tag_name="${GITHUB_REF##*/}"
        for asset in "dvda-author-$tag_name.tar.xz" ./dvda-author-dev.{1,html,pdf}; do
        assets+=("-a" "$asset")
        done
        hub release create  "${assets[@]}" \
        -m "Release $tag_name" 
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
